import { randomBytes } from 'node:crypto'
import { Buffer } from 'node:buffer'
import { credentialKey, type CredentialProvider, type CredentialRecord } from '@deepseek-ai/dsh-credentials'
import { Remote, TypertRemoteService } from '@deepseek-ai/dsh-typert-protocol'
import type { Agent } from '@deepseek-ai/dsh-agent'
import type { Context } from '@deepseek-ai/cordis'
import type { Database } from './database/index.ts'
import { EmbymediaError } from './errors.ts'
import {
  CREDENTIAL_IDS,
  isCredentialId,
  type CredentialGrantRecord,
  type CredentialId,
} from './schemas.ts'

const MAX_CREDENTIAL_BYTES = 64 * 1024
const PENDING_PREFIX = 'pending-'

export interface CredentialStatus {
  readonly id: CredentialId
  readonly configured: boolean
  readonly writable: boolean
  readonly kind?: 'grant'
}

function validateGrant(record: CredentialRecord | undefined, label: string): CredentialGrantRecord | undefined {
  if (record === undefined) return undefined
  if (record.kind !== 'grant' || typeof record.payload !== 'object' || record.payload === null || Array.isArray(record.payload)) {
    throw new EmbymediaError('AUTH_REQUIRED', `${label} has an invalid credential record`)
  }
  const payload = record.payload as Record<string, unknown>
  if (payload.version !== 1 || typeof payload.value !== 'string' || payload.value.length === 0
    || Reflect.ownKeys(payload).some(key => key !== 'version' && key !== 'value')) {
    throw new EmbymediaError('AUTH_REQUIRED', `${label} has an invalid credential record`)
  }
  return { kind: 'grant', payload: { version: 1, value: payload.value } }
}

function credentialFromConfirmation(value: unknown): CredentialId | undefined {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) return undefined
  const input = (value as Record<string, unknown>).input
  if (typeof input !== 'object' || input === null || Array.isArray(input)) return undefined
  const credential = (input as Record<string, unknown>).credential
  return isCredentialId(credential) ? credential : undefined
}

export class EmbymediaCredentialRecords {
  constructor(
    private readonly provider: CredentialProvider,
    private readonly database: Database,
  ) {}

  async read(id: CredentialId): Promise<string> {
    const record = validateGrant(await this.provider.readRecord(credentialKey('embymedia', id)), id)
    if (record === undefined) throw new EmbymediaError('AUTH_REQUIRED', `${id} is not configured`, { credential: id })
    return record.payload.value
  }

  async status(): Promise<readonly CredentialStatus[]> {
    return Promise.all(CREDENTIAL_IDS.map(async (id) => {
      const info = await this.provider.describeRecord(credentialKey('embymedia', id))
      return {
        id,
        configured: info.configured,
        writable: info.writable,
        ...(info.kind === 'grant' ? { kind: info.kind } : {}),
      }
    }))
  }

  async stage(agent: Agent, planId: string, value: string, signal: AbortSignal): Promise<{ configured: true }> {
    signal.throwIfAborted()
    const bytes = Buffer.byteLength(value)
    if (bytes === 0 || bytes > MAX_CREDENTIAL_BYTES || value.includes('\0')) {
      throw new EmbymediaError('INVALID_INPUT', 'credential must be non-empty, NUL-free, and at most 64 KiB')
    }
    const plan = await this.database.query<{
      kind: string
      status: string
      session_id: string
      expires_at: Date
      confirmation: unknown
    }>(
      `SELECT kind,status,session_id,expires_at,confirmation
       FROM operation_plans WHERE id = $1`,
      [planId],
    )
    const row = plan.rows[0]
    if (row === undefined) throw new EmbymediaError('NOT_FOUND', 'credential rotation plan not found')
    if (row.kind !== 'config.credential_rotate' || row.session_id !== agent.id
      || row.status !== 'previewed' || row.expires_at.getTime() <= Date.now()) {
      throw new EmbymediaError('POLICY_DENIED', 'credential rotation plan is not stageable')
    }
    const id = credentialFromConfirmation(row.confirmation)
    if (id === undefined) throw new EmbymediaError('CONFLICT', 'credential rotation plan has invalid confirmation')
    if (id === 'clouddrive-webhook-secret') {
      throw new EmbymediaError('POLICY_DENIED', 'webhook secrets are generated by the Host')
    }
    if (id === 'outbound-proxy-url') {
      let protocol: string
      try {
        protocol = new URL(value).protocol
      } catch {
        throw new EmbymediaError('INVALID_INPUT', 'outbound proxy must be a valid URL')
      }
      if (!['http:', 'https:', 'socks5:', 'socks5h:'].includes(protocol)) {
        throw new EmbymediaError('INVALID_INPUT', 'outbound proxy protocol must be http, https, socks5, or socks5h')
      }
    }
    const pending = credentialKey('embymedia', `${PENDING_PREFIX}${planId}-${id}`)
    await this.provider.modifyRecord(pending, async () => ({
      kind: 'grant',
      payload: { version: 1, value },
    }))
    signal.throwIfAborted()
    return { configured: true }
  }

  async generateWebhookPending(planId: string): Promise<void> {
    const value = randomBytes(32).toString('base64url')
    const pending = credentialKey('embymedia', `${PENDING_PREFIX}${planId}-clouddrive-webhook-secret`)
    await this.provider.modifyRecord(pending, async () => ({ kind: 'grant', payload: { version: 1, value } }))
  }

  async readPending(planId: string, id: CredentialId): Promise<string> {
    const key = credentialKey('embymedia', `${PENDING_PREFIX}${planId}-${id}`)
    const record = validateGrant(await this.provider.readRecord(key), `pending ${id}`)
    if (record === undefined) throw new EmbymediaError('AUTH_REQUIRED', `pending ${id} is not configured`)
    return record.payload.value
  }

  async promotePending(planId: string, id: CredentialId): Promise<void> {
    const value = await this.readPending(planId, id)
    const formal = credentialKey('embymedia', id)
    await this.provider.modifyRecord(formal, async () => ({ kind: 'grant', payload: { version: 1, value } }))
    await this.discardPending(planId, id)
  }

  async discardPending(planId: string, id: CredentialId): Promise<void> {
    await this.provider.deleteRecord(credentialKey('embymedia', `${PENDING_PREFIX}${planId}-${id}`))
  }

  async cleanupOrphans(): Promise<number> {
    const records = await this.provider.listRecords()
    let deleted = 0
    for (const entry of records) {
      const text = String(entry.key)
      if (!text.startsWith(`embymedia/${PENDING_PREFIX}`)) continue
      const planId = text.slice(`embymedia/${PENDING_PREFIX}`.length, `embymedia/${PENDING_PREFIX}`.length + 36)
      const plan = await this.database.query<{ active: boolean }>(
        `SELECT status IN ('previewed','approved') AND expires_at > now() AS active
         FROM operation_plans WHERE id = $1`,
        [planId],
      )
      if (plan.rows[0]?.active === true) continue
      await this.provider.deleteRecord(entry.key)
      deleted++
    }
    return deleted
  }
}

export class EmbymediaSecretsRemote extends TypertRemoteService {
  constructor(ctx: Context, private readonly records: EmbymediaCredentialRecords) {
    super(ctx, 'embymediaSecrets', { namespace: 'embymedia-secrets' })
  }

  @Remote
  async stage(
    agent: Agent,
    planId: string,
    value: string,
    signal: AbortSignal,
  ): Promise<{ configured: true }> {
    return this.records.stage(agent, planId, value, signal)
  }
}
