export const EMBYMEDIA_CARD_TOOLS = [
  'embymedia_health',
  'embymedia_library',
  'embymedia_resource',
  'embymedia_series',
  'embymedia_analyze',
  'embymedia_task',
  'embymedia_audit',
  'embymedia_user',
  'embymedia_schedule',
  'embymedia_config',
  'embymedia_plan',
  'embymedia_execute',
  'embymedia_verify',
] as const
