#!/usr/sbin/nft -f

destroy table inet embymedia_filter

table inet embymedia_filter {
  chain input {
    type filter hook input priority filter; policy drop;

    iifname "lo" accept
    ct state established,related accept
    ct state invalid drop

    ip protocol icmp accept
    ip6 nexthdr ipv6-icmp accept

    tcp dport { 22, 80, 443 } ct state new accept
  }

  chain forward {
    type filter hook forward priority filter; policy drop;
    ct state established,related accept
    iifname "docker0" oifname != "docker0" accept
    iifname "br-*" oifname != "br-*" accept
  }

  chain output {
    type filter hook output priority filter; policy accept;
  }
}
