// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0
// source: internal/clouddrivepb/clouddrive.proto

package clouddrivepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DevicePowerType int32

const (
	DevicePowerType_DESKTOP      DevicePowerType = 0
	DevicePowerType_SLOW_STORAGE DevicePowerType = 1
	DevicePowerType_BATTERY      DevicePowerType = 2
)

// Enum value maps for DevicePowerType.
var (
	DevicePowerType_name = map[int32]string{
		0: "DESKTOP",
		1: "SLOW_STORAGE",
		2: "BATTERY",
	}
	DevicePowerType_value = map[string]int32{
		"DESKTOP":      0,
		"SLOW_STORAGE": 1,
		"BATTERY":      2,
	}
)

func (x DevicePowerType) Enum() *DevicePowerType {
	p := new(DevicePowerType)
	*p = x
	return p
}

func (x DevicePowerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DevicePowerType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_clouddrivepb_clouddrive_proto_enumTypes[0].Descriptor()
}

func (DevicePowerType) Type() protoreflect.EnumType {
	return &file_internal_clouddrivepb_clouddrive_proto_enumTypes[0]
}

func (x DevicePowerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DevicePowerType.Descriptor instead.
func (DevicePowerType) EnumDescriptor() ([]byte, []int) {
	return file_internal_clouddrivepb_clouddrive_proto_rawDescGZIP(), []int{0}
}

type CloudDriveSystemInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IsLogin         bool                   `protobuf:"varint,1,opt,name=is_login,json=isLogin,proto3" json:"is_login,omitempty"`
	UserName        string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	SystemReady     bool                   `protobuf:"varint,3,opt,name=system_ready,json=systemReady,proto3" json:"system_ready,omitempty"`
	SystemMessage   *string                `protobuf:"bytes,4,opt,name=system_message,json=systemMessage,proto3,oneof" json:"system_message,omitempty"`
	HasError        *bool                  `protobuf:"varint,5,opt,name=has_error,json=hasError,proto3,oneof" json:"has_error,omitempty"`
	DevicePowerType DevicePowerType        `protobuf:"varint,6,opt,name=device_power_type,json=devicePowerType,proto3,enum=clouddrive.DevicePowerType" json:"device_power_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CloudDriveSystemInfo) Reset() {
	*x = CloudDriveSystemInfo{}
	mi := &file_internal_clouddrivepb_clouddrive_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudDriveSystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudDriveSystemInfo) ProtoMessage() {}

func (x *CloudDriveSystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clouddrivepb_clouddrive_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudDriveSystemInfo.ProtoReflect.Descriptor instead.
func (*CloudDriveSystemInfo) Descriptor() ([]byte, []int) {
	return file_internal_clouddrivepb_clouddrive_proto_rawDescGZIP(), []int{0}
}

func (x *CloudDriveSystemInfo) GetIsLogin() bool {
	if x != nil {
		return x.IsLogin
	}
	return false
}

func (x *CloudDriveSystemInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CloudDriveSystemInfo) GetSystemReady() bool {
	if x != nil {
		return x.SystemReady
	}
	return false
}

func (x *CloudDriveSystemInfo) GetSystemMessage() string {
	if x != nil && x.SystemMessage != nil {
		return *x.SystemMessage
	}
	return ""
}

func (x *CloudDriveSystemInfo) GetHasError() bool {
	if x != nil && x.HasError != nil {
		return *x.HasError
	}
	return false
}

func (x *CloudDriveSystemInfo) GetDevicePowerType() DevicePowerType {
	if x != nil {
		return x.DevicePowerType
	}
	return DevicePowerType_DESKTOP
}

type RuntimeInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProductName     string                 `protobuf:"bytes,1,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	ProductVersion  string                 `protobuf:"bytes,2,opt,name=product_version,json=productVersion,proto3" json:"product_version,omitempty"`
	CloudApiVersion string                 `protobuf:"bytes,3,opt,name=cloud_api_version,json=cloudApiVersion,proto3" json:"cloud_api_version,omitempty"`
	OsInfo          string                 `protobuf:"bytes,4,opt,name=os_info,json=osInfo,proto3" json:"os_info,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RuntimeInfo) Reset() {
	*x = RuntimeInfo{}
	mi := &file_internal_clouddrivepb_clouddrive_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeInfo) ProtoMessage() {}

func (x *RuntimeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clouddrivepb_clouddrive_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeInfo.ProtoReflect.Descriptor instead.
func (*RuntimeInfo) Descriptor() ([]byte, []int) {
	return file_internal_clouddrivepb_clouddrive_proto_rawDescGZIP(), []int{1}
}

func (x *RuntimeInfo) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *RuntimeInfo) GetProductVersion() string {
	if x != nil {
		return x.ProductVersion
	}
	return ""
}

func (x *RuntimeInfo) GetCloudApiVersion() string {
	if x != nil {
		return x.CloudApiVersion
	}
	return ""
}

func (x *RuntimeInfo) GetOsInfo() string {
	if x != nil {
		return x.OsInfo
	}
	return ""
}

type MountPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountPoint    string                 `protobuf:"bytes,1,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	SourceDir     string                 `protobuf:"bytes,2,opt,name=source_dir,json=sourceDir,proto3" json:"source_dir,omitempty"`
	LocalMount    bool                   `protobuf:"varint,3,opt,name=local_mount,json=localMount,proto3" json:"local_mount,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,4,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	AutoMount     bool                   `protobuf:"varint,5,opt,name=auto_mount,json=autoMount,proto3" json:"auto_mount,omitempty"`
	Uid           uint32                 `protobuf:"varint,6,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint32                 `protobuf:"varint,7,opt,name=gid,proto3" json:"gid,omitempty"`
	Permissions   string                 `protobuf:"bytes,8,opt,name=permissions,proto3" json:"permissions,omitempty"`
	IsMounted     bool                   `protobuf:"varint,9,opt,name=is_mounted,json=isMounted,proto3" json:"is_mounted,omitempty"`
	FailReason    string                 `protobuf:"bytes,10,opt,name=fail_reason,json=failReason,proto3" json:"fail_reason,omitempty"`
	Name          string                 `protobuf:"bytes,11,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountPoint) Reset() {
	*x = MountPoint{}
	mi := &file_internal_clouddrivepb_clouddrive_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountPoint) ProtoMessage() {}

func (x *MountPoint) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clouddrivepb_clouddrive_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountPoint.ProtoReflect.Descriptor instead.
func (*MountPoint) Descriptor() ([]byte, []int) {
	return file_internal_clouddrivepb_clouddrive_proto_rawDescGZIP(), []int{2}
}

func (x *MountPoint) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *MountPoint) GetSourceDir() string {
	if x != nil {
		return x.SourceDir
	}
	return ""
}

func (x *MountPoint) GetLocalMount() bool {
	if x != nil {
		return x.LocalMount
	}
	return false
}

func (x *MountPoint) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *MountPoint) GetAutoMount() bool {
	if x != nil {
		return x.AutoMount
	}
	return false
}

func (x *MountPoint) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *MountPoint) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *MountPoint) GetPermissions() string {
	if x != nil {
		return x.Permissions
	}
	return ""
}

func (x *MountPoint) GetIsMounted() bool {
	if x != nil {
		return x.IsMounted
	}
	return false
}

func (x *MountPoint) GetFailReason() string {
	if x != nil {
		return x.FailReason
	}
	return ""
}

func (x *MountPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MountPointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountPoint    string                 `protobuf:"bytes,1,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountPointRequest) Reset() {
	*x = MountPointRequest{}
	mi := &file_internal_clouddrivepb_clouddrive_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountPointRequest) ProtoMessage() {}

func (x *MountPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clouddrivepb_clouddrive_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountPointRequest.ProtoReflect.Descriptor instead.
func (*MountPointRequest) Descriptor() ([]byte, []int) {
	return file_internal_clouddrivepb_clouddrive_proto_rawDescGZIP(), []int{3}
}

func (x *MountPointRequest) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

type GetMountPointsResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountPoints   []*MountPoint          `protobuf:"bytes,1,rep,name=mount_points,json=mountPoints,proto3" json:"mount_points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMountPointsResult) Reset() {
	*x = GetMountPointsResult{}
	mi := &file_internal_clouddrivepb_clouddrive_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMountPointsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMountPointsResult) ProtoMessage() {}

func (x *GetMountPointsResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clouddrivepb_clouddrive_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMountPointsResult.ProtoReflect.Descriptor instead.
func (*GetMountPointsResult) Descriptor() ([]byte, []int) {
	return file_internal_clouddrivepb_clouddrive_proto_rawDescGZIP(), []int{4}
}

func (x *GetMountPointsResult) GetMountPoints() []*MountPoint {
	if x != nil {
		return x.MountPoints
	}
	return nil
}

type MountPointResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	FailReason    string                 `protobuf:"bytes,2,opt,name=fail_reason,json=failReason,proto3" json:"fail_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountPointResult) Reset() {
	*x = MountPointResult{}
	mi := &file_internal_clouddrivepb_clouddrive_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountPointResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountPointResult) ProtoMessage() {}

func (x *MountPointResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clouddrivepb_clouddrive_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountPointResult.ProtoReflect.Descriptor instead.
func (*MountPointResult) Descriptor() ([]byte, []int) {
	return file_internal_clouddrivepb_clouddrive_proto_rawDescGZIP(), []int{5}
}

func (x *MountPointResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MountPointResult) GetFailReason() string {
	if x != nil {
		return x.FailReason
	}
	return ""
}

var File_internal_clouddrivepb_clouddrive_proto protoreflect.FileDescriptor

const file_internal_clouddrivepb_clouddrive_proto_rawDesc = "" +
	"\n" +
	"&internal/clouddrivepb/clouddrive.proto\x12\n" +
	"clouddrive\x1a\x1bgoogle/protobuf/empty.proto\"\xa9\x02\n" +
	"\x14CloudDriveSystemInfo\x12\x19\n" +
	"\bis_login\x18\x01 \x01(\bR\aisLogin\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12!\n" +
	"\fsystem_ready\x18\x03 \x01(\bR\vsystemReady\x12*\n" +
	"\x0esystem_message\x18\x04 \x01(\tH\x00R\rsystemMessage\x88\x01\x01\x12 \n" +
	"\thas_error\x18\x05 \x01(\bH\x01R\bhasError\x88\x01\x01\x12G\n" +
	"\x11device_power_type\x18\x06 \x01(\x0e2\x1b.clouddrive.DevicePowerTypeR\x0fdevicePowerTypeB\x11\n" +
	"\x0f_system_messageB\f\n" +
	"\n" +
	"_has_error\"\x9e\x01\n" +
	"\vRuntimeInfo\x12!\n" +
	"\fproduct_name\x18\x01 \x01(\tR\vproductName\x12'\n" +
	"\x0fproduct_version\x18\x02 \x01(\tR\x0eproductVersion\x12*\n" +
	"\x11cloud_api_version\x18\x03 \x01(\tR\x0fcloudApiVersion\x12\x17\n" +
	"\aos_info\x18\x04 \x01(\tR\x06osInfo\"\xc3\x02\n" +
	"\n" +
	"MountPoint\x12\x1f\n" +
	"\vmount_point\x18\x01 \x01(\tR\n" +
	"mountPoint\x12\x1d\n" +
	"\n" +
	"source_dir\x18\x02 \x01(\tR\tsourceDir\x12\x1f\n" +
	"\vlocal_mount\x18\x03 \x01(\bR\n" +
	"localMount\x12\x1b\n" +
	"\tread_only\x18\x04 \x01(\bR\breadOnly\x12\x1d\n" +
	"\n" +
	"auto_mount\x18\x05 \x01(\bR\tautoMount\x12\x10\n" +
	"\x03uid\x18\x06 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\a \x01(\rR\x03gid\x12 \n" +
	"\vpermissions\x18\b \x01(\tR\vpermissions\x12\x1d\n" +
	"\n" +
	"is_mounted\x18\t \x01(\bR\tisMounted\x12\x1f\n" +
	"\vfail_reason\x18\n" +
	" \x01(\tR\n" +
	"failReason\x12\x12\n" +
	"\x04name\x18\v \x01(\tR\x04name\"4\n" +
	"\x11MountPointRequest\x12\x1f\n" +
	"\vmount_point\x18\x01 \x01(\tR\n" +
	"mountPoint\"Q\n" +
	"\x14GetMountPointsResult\x129\n" +
	"\fmount_points\x18\x01 \x03(\v2\x16.clouddrive.MountPointR\vmountPoints\"M\n" +
	"\x10MountPointResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vfail_reason\x18\x02 \x01(\tR\n" +
	"failReason*=\n" +
	"\x0fDevicePowerType\x12\v\n" +
	"\aDESKTOP\x10\x00\x12\x10\n" +
	"\fSLOW_STORAGE\x10\x01\x12\v\n" +
	"\aBATTERY\x10\x022\xfb\x02\n" +
	"\x11CloudDriveFileSrv\x12I\n" +
	"\rGetSystemInfo\x12\x16.google.protobuf.Empty\x1a .clouddrive.CloudDriveSystemInfo\x12A\n" +
	"\x0eGetRuntimeInfo\x12\x16.google.protobuf.Empty\x1a\x17.clouddrive.RuntimeInfo\x12J\n" +
	"\x0eGetMountPoints\x12\x16.google.protobuf.Empty\x1a .clouddrive.GetMountPointsResult\x12D\n" +
	"\x05Mount\x12\x1d.clouddrive.MountPointRequest\x1a\x1c.clouddrive.MountPointResult\x12F\n" +
	"\aUnmount\x12\x1d.clouddrive.MountPointRequest\x1a\x1c.clouddrive.MountPointResultB6Z4github.com/embymedia/embymedia/internal/clouddrivepbb\x06proto3"

var (
	file_internal_clouddrivepb_clouddrive_proto_rawDescOnce sync.Once
	file_internal_clouddrivepb_clouddrive_proto_rawDescData []byte
)

func file_internal_clouddrivepb_clouddrive_proto_rawDescGZIP() []byte {
	file_internal_clouddrivepb_clouddrive_proto_rawDescOnce.Do(func() {
		file_internal_clouddrivepb_clouddrive_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_clouddrivepb_clouddrive_proto_rawDesc), len(file_internal_clouddrivepb_clouddrive_proto_rawDesc)))
	})
	return file_internal_clouddrivepb_clouddrive_proto_rawDescData
}

var file_internal_clouddrivepb_clouddrive_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_clouddrivepb_clouddrive_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_clouddrivepb_clouddrive_proto_goTypes = []any{
	(DevicePowerType)(0),         // 0: clouddrive.DevicePowerType
	(*CloudDriveSystemInfo)(nil), // 1: clouddrive.CloudDriveSystemInfo
	(*RuntimeInfo)(nil),          // 2: clouddrive.RuntimeInfo
	(*MountPoint)(nil),           // 3: clouddrive.MountPoint
	(*MountPointRequest)(nil),    // 4: clouddrive.MountPointRequest
	(*GetMountPointsResult)(nil), // 5: clouddrive.GetMountPointsResult
	(*MountPointResult)(nil),     // 6: clouddrive.MountPointResult
	(*emptypb.Empty)(nil),        // 7: google.protobuf.Empty
}
var file_internal_clouddrivepb_clouddrive_proto_depIdxs = []int32{
	0, // 0: clouddrive.CloudDriveSystemInfo.device_power_type:type_name -> clouddrive.DevicePowerType
	3, // 1: clouddrive.GetMountPointsResult.mount_points:type_name -> clouddrive.MountPoint
	7, // 2: clouddrive.CloudDriveFileSrv.GetSystemInfo:input_type -> google.protobuf.Empty
	7, // 3: clouddrive.CloudDriveFileSrv.GetRuntimeInfo:input_type -> google.protobuf.Empty
	7, // 4: clouddrive.CloudDriveFileSrv.GetMountPoints:input_type -> google.protobuf.Empty
	4, // 5: clouddrive.CloudDriveFileSrv.Mount:input_type -> clouddrive.MountPointRequest
	4, // 6: clouddrive.CloudDriveFileSrv.Unmount:input_type -> clouddrive.MountPointRequest
	1, // 7: clouddrive.CloudDriveFileSrv.GetSystemInfo:output_type -> clouddrive.CloudDriveSystemInfo
	2, // 8: clouddrive.CloudDriveFileSrv.GetRuntimeInfo:output_type -> clouddrive.RuntimeInfo
	5, // 9: clouddrive.CloudDriveFileSrv.GetMountPoints:output_type -> clouddrive.GetMountPointsResult
	6, // 10: clouddrive.CloudDriveFileSrv.Mount:output_type -> clouddrive.MountPointResult
	6, // 11: clouddrive.CloudDriveFileSrv.Unmount:output_type -> clouddrive.MountPointResult
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_clouddrivepb_clouddrive_proto_init() }
func file_internal_clouddrivepb_clouddrive_proto_init() {
	if File_internal_clouddrivepb_clouddrive_proto != nil {
		return
	}
	file_internal_clouddrivepb_clouddrive_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_clouddrivepb_clouddrive_proto_rawDesc), len(file_internal_clouddrivepb_clouddrive_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_clouddrivepb_clouddrive_proto_goTypes,
		DependencyIndexes: file_internal_clouddrivepb_clouddrive_proto_depIdxs,
		EnumInfos:         file_internal_clouddrivepb_clouddrive_proto_enumTypes,
		MessageInfos:      file_internal_clouddrivepb_clouddrive_proto_msgTypes,
	}.Build()
	File_internal_clouddrivepb_clouddrive_proto = out.File
	file_internal_clouddrivepb_clouddrive_proto_goTypes = nil
	file_internal_clouddrivepb_clouddrive_proto_depIdxs = nil
}
