// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.0
// source: internal/clouddrivepb/clouddrive.proto

package clouddrivepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CloudDriveFileSrv_GetSystemInfo_FullMethodName  = "/clouddrive.CloudDriveFileSrv/GetSystemInfo"
	CloudDriveFileSrv_GetRuntimeInfo_FullMethodName = "/clouddrive.CloudDriveFileSrv/GetRuntimeInfo"
	CloudDriveFileSrv_GetMountPoints_FullMethodName = "/clouddrive.CloudDriveFileSrv/GetMountPoints"
	CloudDriveFileSrv_Mount_FullMethodName          = "/clouddrive.CloudDriveFileSrv/Mount"
	CloudDriveFileSrv_Unmount_FullMethodName        = "/clouddrive.CloudDriveFileSrv/Unmount"
)

// CloudDriveFileSrvClient is the client API for CloudDriveFileSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CloudDriveFileSrvClient interface {
	GetSystemInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CloudDriveSystemInfo, error)
	GetRuntimeInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RuntimeInfo, error)
	GetMountPoints(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMountPointsResult, error)
	Mount(ctx context.Context, in *MountPointRequest, opts ...grpc.CallOption) (*MountPointResult, error)
	Unmount(ctx context.Context, in *MountPointRequest, opts ...grpc.CallOption) (*MountPointResult, error)
}

type cloudDriveFileSrvClient struct {
	cc grpc.ClientConnInterface
}

func NewCloudDriveFileSrvClient(cc grpc.ClientConnInterface) CloudDriveFileSrvClient {
	return &cloudDriveFileSrvClient{cc}
}

func (c *cloudDriveFileSrvClient) GetSystemInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CloudDriveSystemInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloudDriveSystemInfo)
	err := c.cc.Invoke(ctx, CloudDriveFileSrv_GetSystemInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudDriveFileSrvClient) GetRuntimeInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RuntimeInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeInfo)
	err := c.cc.Invoke(ctx, CloudDriveFileSrv_GetRuntimeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudDriveFileSrvClient) GetMountPoints(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMountPointsResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMountPointsResult)
	err := c.cc.Invoke(ctx, CloudDriveFileSrv_GetMountPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudDriveFileSrvClient) Mount(ctx context.Context, in *MountPointRequest, opts ...grpc.CallOption) (*MountPointResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MountPointResult)
	err := c.cc.Invoke(ctx, CloudDriveFileSrv_Mount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudDriveFileSrvClient) Unmount(ctx context.Context, in *MountPointRequest, opts ...grpc.CallOption) (*MountPointResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MountPointResult)
	err := c.cc.Invoke(ctx, CloudDriveFileSrv_Unmount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CloudDriveFileSrvServer is the server API for CloudDriveFileSrv service.
// All implementations must embed UnimplementedCloudDriveFileSrvServer
// for forward compatibility.
type CloudDriveFileSrvServer interface {
	GetSystemInfo(context.Context, *emptypb.Empty) (*CloudDriveSystemInfo, error)
	GetRuntimeInfo(context.Context, *emptypb.Empty) (*RuntimeInfo, error)
	GetMountPoints(context.Context, *emptypb.Empty) (*GetMountPointsResult, error)
	Mount(context.Context, *MountPointRequest) (*MountPointResult, error)
	Unmount(context.Context, *MountPointRequest) (*MountPointResult, error)
	mustEmbedUnimplementedCloudDriveFileSrvServer()
}

// UnimplementedCloudDriveFileSrvServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCloudDriveFileSrvServer struct{}

func (UnimplementedCloudDriveFileSrvServer) GetSystemInfo(context.Context, *emptypb.Empty) (*CloudDriveSystemInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSystemInfo not implemented")
}
func (UnimplementedCloudDriveFileSrvServer) GetRuntimeInfo(context.Context, *emptypb.Empty) (*RuntimeInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRuntimeInfo not implemented")
}
func (UnimplementedCloudDriveFileSrvServer) GetMountPoints(context.Context, *emptypb.Empty) (*GetMountPointsResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMountPoints not implemented")
}
func (UnimplementedCloudDriveFileSrvServer) Mount(context.Context, *MountPointRequest) (*MountPointResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mount not implemented")
}
func (UnimplementedCloudDriveFileSrvServer) Unmount(context.Context, *MountPointRequest) (*MountPointResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unmount not implemented")
}
func (UnimplementedCloudDriveFileSrvServer) mustEmbedUnimplementedCloudDriveFileSrvServer() {}
func (UnimplementedCloudDriveFileSrvServer) testEmbeddedByValue()                           {}

// UnsafeCloudDriveFileSrvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CloudDriveFileSrvServer will
// result in compilation errors.
type UnsafeCloudDriveFileSrvServer interface {
	mustEmbedUnimplementedCloudDriveFileSrvServer()
}

func RegisterCloudDriveFileSrvServer(s grpc.ServiceRegistrar, srv CloudDriveFileSrvServer) {
	// If the following call pancis, it indicates UnimplementedCloudDriveFileSrvServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CloudDriveFileSrv_ServiceDesc, srv)
}

func _CloudDriveFileSrv_GetSystemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudDriveFileSrvServer).GetSystemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudDriveFileSrv_GetSystemInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudDriveFileSrvServer).GetSystemInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudDriveFileSrv_GetRuntimeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudDriveFileSrvServer).GetRuntimeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudDriveFileSrv_GetRuntimeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudDriveFileSrvServer).GetRuntimeInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudDriveFileSrv_GetMountPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudDriveFileSrvServer).GetMountPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudDriveFileSrv_GetMountPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudDriveFileSrvServer).GetMountPoints(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudDriveFileSrv_Mount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MountPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudDriveFileSrvServer).Mount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudDriveFileSrv_Mount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudDriveFileSrvServer).Mount(ctx, req.(*MountPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudDriveFileSrv_Unmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MountPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudDriveFileSrvServer).Unmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudDriveFileSrv_Unmount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudDriveFileSrvServer).Unmount(ctx, req.(*MountPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CloudDriveFileSrv_ServiceDesc is the grpc.ServiceDesc for CloudDriveFileSrv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CloudDriveFileSrv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clouddrive.CloudDriveFileSrv",
	HandlerType: (*CloudDriveFileSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSystemInfo",
			Handler:    _CloudDriveFileSrv_GetSystemInfo_Handler,
		},
		{
			MethodName: "GetRuntimeInfo",
			Handler:    _CloudDriveFileSrv_GetRuntimeInfo_Handler,
		},
		{
			MethodName: "GetMountPoints",
			Handler:    _CloudDriveFileSrv_GetMountPoints_Handler,
		},
		{
			MethodName: "Mount",
			Handler:    _CloudDriveFileSrv_Mount_Handler,
		},
		{
			MethodName: "Unmount",
			Handler:    _CloudDriveFileSrv_Unmount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/clouddrivepb/clouddrive.proto",
}
