/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        bg: 'var(--bg)',
        'bg-elevated': 'var(--bg-elevated)',
        'bg-muted': 'var(--bg-muted)',
        surface: 'var(--surface)',
        text: 'var(--text)',
        'text-secondary': 'var(--text-secondary)',
        'text-faint': 'var(--text-faint)',
        'text-muted': 'var(--text-muted)',
        border: 'var(--border)',
        'border-strong': 'var(--border-strong)',
        accent: 'var(--accent)',
        'accent-strong': 'var(--accent-strong)',
        'accent-soft': 'var(--accent-soft)',
        'accent-contrast': 'var(--accent-contrast)',
        annotation: 'var(--annotation)',
        'annotation-soft': 'var(--annotation-soft)',
        danger: 'var(--danger)',
        ok: 'var(--ok)',
        warn: 'var(--warn)',
      },
      fontFamily: {
        serif: [
          '"Source Han Serif SC"',
          '"Noto Serif SC"',
          '"Source Han Serif CN"',
          '"Songti SC"',
          'STSong',
          'SimSun',
          'serif',
        ],
        sans: [
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          '"PingFang SC"',
          '"Hiragino Sans GB"',
          '"Noto Sans SC"',
          '"Microsoft YaHei"',
          'sans-serif',
        ],
        mono: [
          '"SFMono-Regular"',
          '"JetBrains Mono"',
          'Menlo',
          'Monaco',
          'Consolas',
          '"Liberation Mono"',
          'monospace',
        ],
      },
      borderRadius: {
        DEFAULT: '8px',
        sm: '6px',
        md: '10px',
        lg: '12px',
        xl: '14px',
        '2xl': '18px',
        '3xl': '24px',
        full: '9999px',
      },
      boxShadow: {
        xs: '0 1px 2px rgba(31, 30, 29, 0.04)',
        sm: '0 1px 3px rgba(31, 30, 29, 0.04), 0 1px 2px rgba(31, 30, 29, 0.02)',
        DEFAULT: '0 2px 6px -1px rgba(31, 30, 29, 0.05), 0 1px 3px -1px rgba(31, 30, 29, 0.03)',
        md: '0 4px 12px -2px rgba(31, 30, 29, 0.06), 0 2px 6px -1px rgba(31, 30, 29, 0.03)',
        lg: '0 10px 24px -4px rgba(31, 30, 29, 0.07), 0 4px 8px -2px rgba(31, 30, 29, 0.03)',
        xl: '0 18px 36px -6px rgba(31, 30, 29, 0.08), 0 6px 14px -3px rgba(31, 30, 29, 0.03)',
        card: '0 1px 3px rgba(31, 30, 29, 0.04), 0 4px 14px -2px rgba(31, 30, 29, 0.04)',
        elevated: '0 3px 8px rgba(31, 30, 29, 0.04), 0 12px 28px -4px rgba(31, 30, 29, 0.07)',
        inner: 'inset 0 1px 2px rgba(31, 30, 29, 0.04)',
      },
      letterSpacing: {
        tighter: '-0.03em',
        tight: '-0.015em',
        normal: '0',
        wide: '0.015em',
        wider: '0.04em',
        widest: '0.08em',
      },
      transitionTimingFunction: {
        'claude-ease': 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
    },
  },
  plugins: [],
}
